BTW Author: Nicholas Carnival
BTW Date: 10/17/18

BTW 'BTW' is how you declare comments

HAI 1.2			BTW DECLATES THE FUNCTION
  CAN HAS STDIO?		BTW DECLARES STANDARD
  VISIBLE "HAI WORLD!!!1!"	BTW PRINTS HAI WORLD
KTHXBYE 			BTW END THE PROGRAM
